FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY packages/admin/package*.json ./packages/admin/
COPY packages/shared/package*.json ./packages/shared/

RUN npm install

COPY packages/admin ./packages/admin
COPY packages/shared ./packages/shared
COPY tsconfig.json ./

RUN npm run build --workspace=packages/shared
RUN npm run build --workspace=packages/admin

RUN chown -R node:node /app
USER node

EXPOSE 4002

CMD ["node", "packages/admin/dist/index.js"]
