FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY packages/collector/package*.json ./packages/collector/
COPY packages/shared/package*.json ./packages/shared/

RUN npm install

COPY packages/collector ./packages/collector
COPY packages/shared ./packages/shared
COPY tsconfig.json ./

RUN npm run build --workspace=packages/shared
RUN npm run build --workspace=packages/collector

RUN chown -R node:node /app
USER node

EXPOSE 4000

CMD ["node", "packages/collector/dist/index.js"]
