FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY packages/api/package*.json ./packages/api/
COPY packages/shared/package*.json ./packages/shared/

RUN npm install

COPY packages/api ./packages/api
COPY packages/shared ./packages/shared
COPY tsconfig.json ./

RUN npm run build --workspace=packages/shared
RUN npm run build --workspace=packages/api

RUN chown -R node:node /app
USER node

EXPOSE 3000

CMD ["node", "packages/api/dist/index.js"]
