FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY packages/processor/package*.json ./packages/processor/
COPY packages/shared/package*.json ./packages/shared/

RUN npm install

COPY packages/processor ./packages/processor
COPY packages/shared ./packages/shared
COPY tsconfig.json ./

RUN npm run build --workspace=packages/shared
RUN npm run build --workspace=packages/processor

RUN chown -R node:node /app
USER node

CMD ["node", "packages/processor/dist/index.js"]
