FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY packages/users/package*.json ./packages/users/
COPY packages/shared/package*.json ./packages/shared/

RUN npm install

COPY packages/users ./packages/users
COPY packages/shared ./packages/shared
COPY tsconfig.json ./

RUN npm run build --workspace=packages/shared
RUN npm run build --workspace=packages/users

RUN chown -R node:node /app
USER node

EXPOSE 4001

CMD ["node", "packages/users/dist/index.js"]
