import { Router, Request, Response } from 'express';
import { pool } from '../database';
import { Logger } from '@hermes/shared';

const router = Router();
const logger = new Logger('AnomaliesAPI');

// Read-only: anomalies are system-generated by packages/intelligence, not
// user-editable, so there's no adminAuth gate here (unlike alerts.ts).

// GET /api/v1/anomalies - Listar anomalias detectadas
router.get('/', async (req: Request, res: Response) => {
    try {
        const {
            appName,
            metricName,
            severity,
            from,
            to,
            limit = '100'
        } = req.query;

        let query = `
            SELECT
                id,
                time,
                app_name,
                metric_name,
                value,
                expected_value,
                anomaly_score,
                severity,
                algorithm,
                detected_at,
                metadata
            FROM anomalies
            WHERE 1=1
        `;
        const params: any[] = [];
        let paramIndex = 1;

        if (appName) {
            query += ` AND app_name = $${paramIndex++}`;
            params.push(appName);
        }

        if (metricName) {
            query += ` AND metric_name = $${paramIndex++}`;
            params.push(metricName);
        }

        if (severity) {
            query += ` AND severity = $${paramIndex++}`;
            params.push(severity);
        }

        if (from) {
            query += ` AND time >= to_timestamp($${paramIndex++})`;
            params.push(Number(from) / 1000);
        }

        if (to) {
            query += ` AND time <= to_timestamp($${paramIndex++})`;
            params.push(Number(to) / 1000);
        }

        query += ` ORDER BY time DESC LIMIT $${paramIndex++}`;
        params.push(Number(limit));

        const result = await pool.query(query, params);

        logger.debug(`Fetched ${result.rows.length} anomalies`, { appName, metricName, severity });

        res.json({
            anomalies: result.rows,
            count: result.rows.length
        });

    } catch (error: any) {
        logger.error('Error fetching anomalies:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

// GET /api/v1/anomalies/:id - Detalhes de uma anomalia
router.get('/:id', async (req: Request, res: Response) => {
    try {
        const { id } = req.params;

        const result = await pool.query('SELECT * FROM anomalies WHERE id = $1', [id]);

        if (result.rows.length === 0) {
            return res.status(404).json({ error: 'Anomaly not found' });
        }

        res.json(result.rows[0]);

    } catch (error: any) {
        logger.error('Error fetching anomaly:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
});

export { router as anomaliesRouter };
